In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset
from torchvision.models import resnet18
from PIL import Image
import os

In [2]:
# Load the saved model
model = resnet18(pretrained=False)
num_ftrs = model.fc.in_features
model.fc = nn.Linear(num_ftrs, 2)  # Adjust num_classes according to your dataset
model.load_state_dict(torch.load('resnet_model.pth'))


c:\Users\chuon\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
c:\Users\chuon\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


<All keys matched successfully>

In [4]:
import cv2
import torch
import torch.nn.functional as F
from torchvision import transforms
from PIL import Image

# Load the model (assuming 'model' is defined and loaded previously)
#model = ...

# Define transforms to preprocess the image
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Initialize the camera
cap = cv2.VideoCapture(0)  # 0 indicates the default camera

while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    
    # Convert the frame to a PIL Image
    image = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))

    # Preprocess the image
    input_image = transform(image)
    input_image = input_image.unsqueeze(0)  # Add batch dimension

    # Perform inference
    with torch.no_grad():
        output = model(input_image)

    # Convert the output probabilities to predicted class
    probabilities = F.softmax(output, dim=1)
    predicted_class = torch.argmax(probabilities, dim=1).item()
    print(probabilities)
    # Get the class label
    class_labels = ['another', 'black']  # Replace with your class labels
    predicted_label = class_labels[predicted_class]

    # Display the frame with predicted class label
    cv2.putText(frame, predicted_label, (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)
    cv2.imshow('Frame', frame)

    # Press 'q' to exit
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release the camera and close all windows
cap.release()
cv2.destroyAllWindows()


tensor([[0.2447, 0.7553]])
tensor([[0.2469, 0.7531]])
tensor([[0.2373, 0.7627]])
tensor([[0.2388, 0.7612]])
tensor([[0.2300, 0.7700]])
tensor([[0.2386, 0.7614]])
tensor([[0.2395, 0.7605]])
tensor([[0.2439, 0.7561]])
tensor([[0.2445, 0.7555]])
tensor([[0.2436, 0.7564]])
tensor([[0.2442, 0.7558]])
tensor([[0.2281, 0.7719]])
tensor([[0.2658, 0.7342]])
tensor([[0.2358, 0.7642]])
tensor([[0.2494, 0.7506]])
tensor([[0.2415, 0.7585]])
tensor([[0.2479, 0.7521]])
tensor([[0.2282, 0.7718]])
tensor([[0.2396, 0.7604]])
tensor([[0.2415, 0.7585]])
tensor([[0.2438, 0.7562]])
tensor([[0.2383, 0.7617]])
tensor([[0.2515, 0.7485]])
tensor([[0.2425, 0.7575]])
tensor([[0.2253, 0.7747]])
tensor([[0.2414, 0.7586]])
tensor([[0.2362, 0.7638]])
tensor([[0.2295, 0.7705]])
tensor([[0.2369, 0.7631]])
tensor([[0.2399, 0.7601]])
tensor([[0.2380, 0.7620]])
tensor([[0.2441, 0.7559]])
tensor([[0.2299, 0.7701]])
tensor([[0.2238, 0.7762]])
tensor([[0.2188, 0.7812]])
tensor([[0.2473, 0.7527]])
tensor([[0.2303, 0.7697]])
t